### ISSUE TITLE
ILS intercept is inconsistent

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#2]
When an aircraft has been cleared for ILS and is +/- 30deg of runway angle, the aircraft should show a path that is on the localizer.

this is an incorrect path:
<img width="400" alt="screen shot 2016-10-02 at 7 59 27 pm" src="https://cloud.githubusercontent.com/assets/3325985/19025210/de4ffb26-88da-11e6-8d7f-5c2ba1679bc3.png">

but then other times it looks correct:
<img width="328" alt="screen shot 2016-10-02 at 8 03 02 pm" src="https://cloud.githubusercontent.com/assets/3325985/19025228/53969f98-88db-11e6-8f54-0904b50accaa.png">

**Comment by erikquinn** [comment]
Since you bring this up, there is a longstanding (and undocumented, because Erik sucks) issue that's closely related: something in the localizer interception logic isn't working right when you give the turn and clearance at the same time, eg `fh250 *28r [enter]` as opposed to `fh250 [enter] *28r [enter]`. There's some squirrelly behavior with that as well, particularly when in close lateral proximity to the localizer, whereas there are never any such issues if the commands are entered separately.

**Comment by n8rzz** [comment]
Hmm, I can say that chaining commands _does_ work with something like `fh260 ils 28r` on ksfo.  

I'll have to try that and see what's going on there.

**Comment by erikquinn** [comment]
Right, it works, but the interception logic being applied in that situation must be different than when the heading assignment is preexisting, because an occasional bit of weirdness comes up where the airplane does a bunch of loops before intercepting, but this never takes place if you enter them separately. Doesn't make sense based on looking at the code, but nonetheless it's an easily observable behavior. Probably easier if I made a quick screen capture video of it to demonstrate.

**Comment by n8rzz** [comment]
I see what you're saying.  I'll see what I can dig up on this one.
