### ISSUE TITLE
Refactor FMS

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#256]
placeholder issue for what will certainly be a lot of work.

poc of new fms: http://codepen.io/n8rzz/pen/LxZPZW?editors=0010

- [ ] accept a `routeString` or a collection of `FixModels` on instantiation
- [ ] add helper functions that can build `Leg`s and `Waypoint`s from a routeString
- [ ] make heading, speed altitude class properties _informed_ by fix restrictions
- [ ] consolidate `StandardRouteWaypointModel`, `Waypoint` and `FixModel`
    - this will likely necessitate a builder method within `FixModel` that can build a `Waypoint`
    - `StandardRouteWaypointModel` seems duplicative of `Waypoint`
- [ ] add method to `FixCollection` to generate new pooled `PositionModel` from coordinates that uses stored reference position

**Comment by erikquinn** [comment]
Separate the MCP from the FMS. The FMS should be rarely altered; only really during reroutes (such as SID/STAR/TRXN/IAP assignments), and this means that when we tell an airplane to fly a particular heading, that *does not qualify as a reroute*, and yet that is how it is treated currently, as everything is done with waypoints. This also creates a much tighter parallel with reality, and allows for us to do common things such as enabling LNAV, VNAV, and speed all independently, and in a way that airplane people could make sense of, because that is how it works in real aircraft.

More on this later.

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#139
